### ISSUE TITLE
VMAntiKill is having troubles with my Windows XP

### ISSUE THREAD

**Issue by ghost** [DS1NC-DesConnet/VMAntiKill#2]
### Hey there!

I have been playing with VMAntiKill on my virtual machine (VMware Workstation, not CollabVM) running Microsoft Windows XP (not original OS, but ZverCD 2013.11) and have noticed some bugs and issues in the program. _Some bugs are not too critical, and some are very serious._

1) "Unblock Apps" window is **NOT a dialog, but sizable window**. I can't stretch it as I want, but I can maximize it to fill my screen!
2) Just for fun I disabled ALL applications available in VMAntiKill (CMD, VBScript, DiskPart, MSOobe, etc.) and later I unblocked everything. **The system works well, except CMD - it is DISABLED. Also VMAntiKill says that my TaskMgr is disabled, however, it's not.**
3) Not a bug, but a notice: in "Antivirus Installer" and "Unblock Apps", there is **no "Back to main window" button which returns user to the main program window** ("VMAntiKill..."). IMHO, this is not so comfortable to restart VMAntiKill every time when you want to install some AVs and block some apps in 3-4 mouse clicks (= without restarting program).

_The program is cool, but... I think it can be useful not only for CollabVM protection, but just for Windows NT protection, so that's why I would prefer to call it "WinAntiKill" or "NTAntiKill"..._

That's all for now. Looking forward for your reply! ;)
Best wishes, Ivan Movchan (NobootRecord)

![1](https://user-images.githubusercontent.com/80192956/182191330-4a3f1816-5a25-4c33-a1e1-cd39fdbe7947.png)
![2](https://user-images.githubusercontent.com/80192956/182191335-a0bd8361-867a-491b-8c8a-c9d66fd7b6e3.png)
![3](https://user-images.githubusercontent.com/80192956/182191336-a6a46ecb-550d-420c-8afd-ade0c1ad7abb.png)
![4](https://user-images.githubusercontent.com/80192956/182191337-86ba8119-871f-4cc0-a392-39bcdb52b9c8.png)

**Comment by theDesConnet** [comment]
Soon i fix this
Thx :)
